//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeppolPreClient.net.xledger.peppolclient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="net.xledger.peppolclient.IAccessPointClientService")]
    public interface IAccessPointClientService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessPointClientService/SendMessage", ReplyAction="http://tempuri.org/IAccessPointClientService/SendMessageResponse")]
        PeppolPreClient.net.xledger.peppolclient.SendMessageResponse SendMessage(PeppolPreClient.net.xledger.peppolclient.SendMessageRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessPointClientService/SendMessage", ReplyAction="http://tempuri.org/IAccessPointClientService/SendMessageResponse")]
        System.Threading.Tasks.Task<PeppolPreClient.net.xledger.peppolclient.SendMessageResponse> SendMessageAsync(PeppolPreClient.net.xledger.peppolclient.SendMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessPointClientService/SmlLookup", ReplyAction="http://tempuri.org/IAccessPointClientService/SmlLookupResponse")]
        PeppolPreClient.net.xledger.peppolclient.SmlLookupResponse SmlLookup(PeppolPreClient.net.xledger.peppolclient.SmlLookupRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessPointClientService/SmlLookup", ReplyAction="http://tempuri.org/IAccessPointClientService/SmlLookupResponse")]
        System.Threading.Tasks.Task<PeppolPreClient.net.xledger.peppolclient.SmlLookupResponse> SmlLookupAsync(PeppolPreClient.net.xledger.peppolclient.SmlLookupRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessPointClientService/VefaValidation", ReplyAction="http://tempuri.org/IAccessPointClientService/VefaValidationResponse")]
        PeppolPreClient.net.xledger.peppolclient.VefaValidationResponse VefaValidation(PeppolPreClient.net.xledger.peppolclient.VefaValidationRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessPointClientService/VefaValidation", ReplyAction="http://tempuri.org/IAccessPointClientService/VefaValidationResponse")]
        System.Threading.Tasks.Task<PeppolPreClient.net.xledger.peppolclient.VefaValidationResponse> VefaValidationAsync(PeppolPreClient.net.xledger.peppolclient.VefaValidationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessPointClientService/Ping", ReplyAction="http://tempuri.org/IAccessPointClientService/PingResponse")]
        string Ping();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessPointClientService/Ping", ReplyAction="http://tempuri.org/IAccessPointClientService/PingResponse")]
        System.Threading.Tasks.Task<string> PingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessPointClientService/PingAccessPointService", ReplyAction="http://tempuri.org/IAccessPointClientService/PingAccessPointServiceResponse")]
        string PingAccessPointService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessPointClientService/PingAccessPointService", ReplyAction="http://tempuri.org/IAccessPointClientService/PingAccessPointServiceResponse")]
        System.Threading.Tasks.Task<string> PingAccessPointServiceAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMessage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sSender;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sReceiver;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string sDocumentID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string sProfileID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string sXmlBody;
        
        public SendMessageRequest() {
        }
        
        public SendMessageRequest(string sSender, string sReceiver, string sDocumentID, string sProfileID, string sXmlBody) {
            this.sSender = sSender;
            this.sReceiver = sReceiver;
            this.sDocumentID = sDocumentID;
            this.sProfileID = sProfileID;
            this.sXmlBody = sXmlBody;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMessageResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public long SendMessageResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sErrorInfo;
        
        public SendMessageResponse() {
        }
        
        public SendMessageResponse(long SendMessageResult, string sErrorInfo) {
            this.SendMessageResult = SendMessageResult;
            this.sErrorInfo = sErrorInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SmlLookup", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SmlLookupRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sRecipientValue;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sDocumentID;
        
        public SmlLookupRequest() {
        }
        
        public SmlLookupRequest(string sRecipientValue, string sDocumentID) {
            this.sRecipientValue = sRecipientValue;
            this.sDocumentID = sDocumentID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SmlLookupResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SmlLookupResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool SmlLookupResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sErrorInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string sEndpoint;
        
        public SmlLookupResponse() {
        }
        
        public SmlLookupResponse(bool SmlLookupResult, string sErrorInfo, string sEndpoint) {
            this.SmlLookupResult = SmlLookupResult;
            this.sErrorInfo = sErrorInfo;
            this.sEndpoint = sEndpoint;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VefaValidation", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class VefaValidationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sFile;
        
        public VefaValidationRequest() {
        }
        
        public VefaValidationRequest(string sFile) {
            this.sFile = sFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VefaValidationResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class VefaValidationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool VefaValidationResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sErrorInfo;
        
        public VefaValidationResponse() {
        }
        
        public VefaValidationResponse(bool VefaValidationResult, string sErrorInfo) {
            this.VefaValidationResult = VefaValidationResult;
            this.sErrorInfo = sErrorInfo;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccessPointClientServiceChannel : PeppolPreClient.net.xledger.peppolclient.IAccessPointClientService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccessPointClientServiceClient : System.ServiceModel.ClientBase<PeppolPreClient.net.xledger.peppolclient.IAccessPointClientService>, PeppolPreClient.net.xledger.peppolclient.IAccessPointClientService {
        
        public AccessPointClientServiceClient() {
        }
        
        public AccessPointClientServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccessPointClientServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccessPointClientServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccessPointClientServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PeppolPreClient.net.xledger.peppolclient.SendMessageResponse PeppolPreClient.net.xledger.peppolclient.IAccessPointClientService.SendMessage(PeppolPreClient.net.xledger.peppolclient.SendMessageRequest request) {
            return base.Channel.SendMessage(request);
        }
        
        public long SendMessage(string sSender, string sReceiver, string sDocumentID, string sProfileID, string sXmlBody, out string sErrorInfo) {
            PeppolPreClient.net.xledger.peppolclient.SendMessageRequest inValue = new PeppolPreClient.net.xledger.peppolclient.SendMessageRequest();
            inValue.sSender = sSender;
            inValue.sReceiver = sReceiver;
            inValue.sDocumentID = sDocumentID;
            inValue.sProfileID = sProfileID;
            inValue.sXmlBody = sXmlBody;
            PeppolPreClient.net.xledger.peppolclient.SendMessageResponse retVal = ((PeppolPreClient.net.xledger.peppolclient.IAccessPointClientService)(this)).SendMessage(inValue);
            sErrorInfo = retVal.sErrorInfo;
            return retVal.SendMessageResult;
        }
        
        public System.Threading.Tasks.Task<PeppolPreClient.net.xledger.peppolclient.SendMessageResponse> SendMessageAsync(PeppolPreClient.net.xledger.peppolclient.SendMessageRequest request) {
            return base.Channel.SendMessageAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PeppolPreClient.net.xledger.peppolclient.SmlLookupResponse PeppolPreClient.net.xledger.peppolclient.IAccessPointClientService.SmlLookup(PeppolPreClient.net.xledger.peppolclient.SmlLookupRequest request) {
            return base.Channel.SmlLookup(request);
        }
        
        public bool SmlLookup(string sRecipientValue, string sDocumentID, out string sErrorInfo, out string sEndpoint) {
            PeppolPreClient.net.xledger.peppolclient.SmlLookupRequest inValue = new PeppolPreClient.net.xledger.peppolclient.SmlLookupRequest();
            inValue.sRecipientValue = sRecipientValue;
            inValue.sDocumentID = sDocumentID;
            PeppolPreClient.net.xledger.peppolclient.SmlLookupResponse retVal = ((PeppolPreClient.net.xledger.peppolclient.IAccessPointClientService)(this)).SmlLookup(inValue);
            sErrorInfo = retVal.sErrorInfo;
            sEndpoint = retVal.sEndpoint;
            return retVal.SmlLookupResult;
        }
        
        public System.Threading.Tasks.Task<PeppolPreClient.net.xledger.peppolclient.SmlLookupResponse> SmlLookupAsync(PeppolPreClient.net.xledger.peppolclient.SmlLookupRequest request) {
            return base.Channel.SmlLookupAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PeppolPreClient.net.xledger.peppolclient.VefaValidationResponse PeppolPreClient.net.xledger.peppolclient.IAccessPointClientService.VefaValidation(PeppolPreClient.net.xledger.peppolclient.VefaValidationRequest request) {
            return base.Channel.VefaValidation(request);
        }
        
        public bool VefaValidation(string sFile, out string sErrorInfo) {
            PeppolPreClient.net.xledger.peppolclient.VefaValidationRequest inValue = new PeppolPreClient.net.xledger.peppolclient.VefaValidationRequest();
            inValue.sFile = sFile;
            PeppolPreClient.net.xledger.peppolclient.VefaValidationResponse retVal = ((PeppolPreClient.net.xledger.peppolclient.IAccessPointClientService)(this)).VefaValidation(inValue);
            sErrorInfo = retVal.sErrorInfo;
            return retVal.VefaValidationResult;
        }
        
        public System.Threading.Tasks.Task<PeppolPreClient.net.xledger.peppolclient.VefaValidationResponse> VefaValidationAsync(PeppolPreClient.net.xledger.peppolclient.VefaValidationRequest request) {
            return base.Channel.VefaValidationAsync(request);
        }
        
        public string Ping() {
            return base.Channel.Ping();
        }
        
        public System.Threading.Tasks.Task<string> PingAsync() {
            return base.Channel.PingAsync();
        }
        
        public string PingAccessPointService() {
            return base.Channel.PingAccessPointService();
        }
        
        public System.Threading.Tasks.Task<string> PingAccessPointServiceAsync() {
            return base.Channel.PingAccessPointServiceAsync();
        }
    }
}
